name: ci

on:
  push:
    branches:
      - "dev"
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      DOCKER_IMAGE_NAME: "authenticate-service"
      WORK_DIR: ${{ github.workspace }}

    steps:
      - name: Set environment
        run: |
          cd ..
          ls -la "${GITHUB_WORKSPACE}"
          ls -la "${{ env.WORK_DIR }}"
          version=$(cat ${{ env.WORK_DIR }}/version || echo "latest")
          echo $version
          echo "DOCKER_IMAGE_TAG=${version}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.WORK_DIR }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
